name: Build desktop apps

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build macOS amd64
      run: GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -v -o bin/mg_mac_intel

    - name: Build macOS arm64
      run: GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -v -o bin/mg_mac_silicon

    - name: Build Linux amd64
      run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -o bin/mg_linux_amd64

    - name: Build Linux arm64
      run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -v -o bin/mg_linux_arm64

    - name: Build Windows amd64
      run: GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -v -o bin/mg_win_amd64.exe

    - name: Build Windows arm64
      run: GOOS=windows GOARCH=arm64 CGO_ENABLED=0 go build -v -o bin/mg_win_arm64.exe

    - name: Upload artifcats to release 
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/**"
        token: ${{ secrets.GITHUB_TOKEN }}